config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/nodes/:key', to: 'nodes#index'

  resources :nodes, only: :create

  post '/nodes/create_child', to: 'nodes#create_child'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  validates :name, :presence => true
  validates :key, :presence => true

  before_validation :generate_key

  def generate_key
    key_check = true
    key = ""
    while key_check
      key = SecureRandom.urlsafe_base64 25
      key_check = false unless Map.find_by_key key
    end
    self.key = key
  end
end

app/models/node.rb
class Node < ApplicationRecord
  has_ancestry
  validates :name, :presence => true
  validates :key, :presence => true

  before_validation :generate_key

  def generate_key
    key_check = true
    key = ""
    while key_check
      key = SecureRandom.urlsafe_base64 25
      key_check = false unless Node.find_by_key key
    end
    self.key = key
  end

  def get_url
    request.domain + '/nodes/' + self.key
  end

  def get_chain_string
    return "#{self.name} " if self.root?
    self.parent.get_chain_string + " > #{self.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def index
    @key = params[:key]
    @node = Node.find_by_key @key
    @name = @node.name if @node
  end

  def create
  	name = params[:name]
  	@node = Node.create(name: name)
  	redirect_to "/nodes/#{@node.key}"
  end

  def create_child
  	name = params[:name]
  	@node = Node.new(name: name)
  	parent = Node.find_by_key params[:parent_key]
  	if parent
  		@node.parent = parent
  		@node.save
  		redirect_to "/nodes/#{@node.key}"
  	end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sixthdegree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nodes/index.html.erb
<h1>Welcome to <%= @node.name %>'s page, mate.</h1>
<h2><%= @node.get_chain_string %></h2>

<div>
  <div><p><%= @node.name %>'s children:</p></div>
  <% for child in @node.children do %>
    <div>
      <p><%= child.name %></p>
    </div>
  <% end %>
</div>

<p> Add to the network!</p>

<%= form_tag nodes_create_child_path do %>
  <%= hidden_field_tag(:parent_key, @node.key) %>
  <%= label_tag(:name, "Enter your name") %>
  <%= text_field_tag(:name) %>
  <%= submit_tag "Submit" %>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Sixth Degree!</h1>
<h2>How many friends do YOU have?<h2>
<p>Cool background information about how we are all connected</p>

<%= form_tag :controller => 'nodes', :action => 'create' do %>
  <%= label_tag(:name, "Enter your name") %>
  <%= text_field_tag(:name) %>
  <%= submit_tag "Submit" %>
	
<% end %>